# Generated by Django 3.2.9 on 2021-11-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='display_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default='anonymous', max_length=256),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.CharField(choices=[('YES', 'Absolutely!'), ('UNS', 'Not quite certain'), ('NO', 'Unfortunately, no')], max_length=3),
        ),
    ]
