# Generated by Django 3.2.9 on 2021-11-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20211110_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.CharField(choices=[('Absolutely!', 'YES'), ('Unsure', 'UNS'), ('Nope', 'NO!')], max_length=20),
        ),
    ]
