# Generated by Django 3.2.9 on 2021-11-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_guest_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.CharField(choices=[('YES', 'Absolutely!'), ('UNS', 'Not quite certain'), ('NO', 'Unfortunately, no')], max_length=20),
        ),
    ]
