# Generated by Django 3.2.9 on 2021-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_guest_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp',
            field=models.CharField(choices=[('Yes!', 'Yes!'), ('Unsure', 'Unsure'), ('No', 'No')], default='Unsure', max_length=30),
        ),
    ]
